baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Jordan White"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

        #Menus:
        #  main:
        #    - identifier: blog
        #      name: Blog
        #      title: Blog posts
        #      url: /blogs
        #      weight: 1
        #    - identifier: gallery
        #      name: Gallery
        #      title: Blog posts
        #      url: /gallery
        #      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Jordan White"
  description: Musician, Organiser, Teacher
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
     disableThemeToggle: true
     defaultTheme: "dark" # light

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Jordan White" # Brand name for the brand | default is the title variable
    disableSearch: true # false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
      #  intro: "Hi, my name is"
    title: "Jordan White"
    subtitle: "Website currently under reconstruction!"
    content: "Musician, Organiser, Teacher"
    image: /images/header.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-bandcamp
          url: https://jordan-white.bandcamp.com/
        - icon: fab fa-youtube
          url: https://www.youtube.com/@jordanwhite100
        - icon: fab fa-instagram
          url: https://www.instagram.com/imjordanwhite11
            #      customIcons:
            #- icon: /fav.png
            #url: "https://example.com"
    # just seeing if this works for now
  
            #{{< bandcamp 3833210465 >}}

            #  {{< youtube pP3xl4xRJAY >}}

  # About
  about:
    enable: true
    title: "G'day!"
      #image: "/images/header.jpg"
    content: |-
      I'm a guitarist, composer, improviser, organiser and teacher. I'm from Orange, NSW, Australia, but have lived in Melbourne, Leipzig and Weimar, and now live in Cologne, Germany.

      I play and compose jazz music, and I work as a solo artist both with guitar and SuperCollider. I curate and organise the festival and concert series Come Closer together with my dear friend Peter Ehwald, and I'm currently on the jury of the Musikfonds e.V.

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: White-Reznichenko Quintet
        content: High-energy modern jazz - five strongly contrasting personalities making equally contrasting music.
        image: /images/olgajordan.jpg
        featured:
          name: More...
          link: /music/white-reznichenko
        badges:
          - "Music"
          - "Jazz"
        links:
          - icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=pP3xl4xRJAY

      - title: Solo
        content: Experimental jazz and electroacoustic music with guitar and SuperCollider
        image: /images/solo.jpg
        featured:
          name: More...
          link: /music/solo
        badges:
          - "Music"
          - "Experimental"
        links:
          - icon: fab fa-bandcamp
            url: https://jordan-white.bandcamp.com/album/live-klangrausch
          - icon: fab fa-youtube
            url: https://www.youtube.com/watch?app=desktop&v=6VpF7hmT5Gg

      - title: Come Closer
        content: A festival and concert series in Weimar and Thuringia, aimed at strengthening the jazz scene in central Germany
        image: /images/comecloser.jpg
        featured:
          name: More...
          link: https://comecloserweimar.eu
        badges:
          - "Jazz"
          - "Curation"
          - "Festival"
        links:
          - icon: fab fa-youtube
            url: https://www.youtube.com/watch?app=desktop&v=6VpF7hmT5Gg
          - icon: fab fa-instagram
            url: https://www.instagram.com/come_closer_weimar/

  # other projects - why is this in light mode?
  achievements: 
    enable: true
    title: "Other Projects I've Worked On"
    items:
      - title: Other Music Academy
        content: A centre for sociocultural and musical work, being built alongside the restoration of a beautiful old house in Weimar. I've been involved since late 2018, curating, organising, producing and performing several hundred concerts and other events.
        image: /images/oma.jpg
        featured: 
          name: More...
          link: https://othermusicacademy.eu/en/
        badges:
          - "Culture"
          - "Project Management"
          - "Curation"
        links:
          - icon: fab fa-instagram
            url: https://www.instagram.com/othermusicacademy/
        
      - title: Yiddish Summer Weimar
        content: One of the world's most important festivals for Yiddish Culture. I was heavily involved in this festival from 2019 - 2023 and took over Production of the festival in 2021.
        image: /images/ysw.jpg
        featured:
          name: More...
          link: https://yiddishsummer.eu
        badges:
          - "Culture"
          - "Project Management"
          - "Production"
        links:
          - icon: fab fa-instagram
            url: https://www.instagram.com/yiddishsummerweimar/

      - title: YoWo Music
        content: A project for teenage girls and queer teens to be coached in contemporary music. I helped found YoWo back in 2015, although most of the heavy lifting really occured after I moved to Germany in mid-2016 - but I'm still super proud of what it's become!
        image: /images/yowo.jpg
        featured:
          name: More...
          link: https://www.yowomusic.com/
          badges: 
            - "Project Management"
            - "Culture"
          links: 
            - icon: fab fa-instagram
              url: https://www.instagram.com/yowomusic/
            - icon: fab fa-bandcamp
              url: https://yowomusic.bandcamp.com/music

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Feel free to send me an email!
    btnName: Email me
    btnLink: mailto:jordanwhitede@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false  

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
